import React, { useState } from 'react';
import { startRun } from '../utils/api';

export default function RunPage({ setScreen, setCurrentRunId }) {
    const [form, setForm] = useState({
        github_url: '',
        team_name: '',
        leader_name: ''
    });
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState('');

    // Auto-generate branch name from team and leader names
    // Format: TEAMNAME_LEADERNAME_AI_Fix (all uppercase, spaces → underscores)
    const generateBranchName = (teamName, leaderName) => {
        if (!teamName && !leaderName) return '';
        
        // Convert to uppercase and replace spaces with underscores
        const team = teamName.toUpperCase().replace(/\s+/g, '_').replace(/[^A-Z0-9_]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
        const leader = leaderName.toUpperCase().replace(/\s+/g, '_').replace(/[^A-Z0-9_]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
        
        if (!team && !leader) return '';
        if (!team) return `${leader}_AI_Fix`;
        if (!leader) return `${team}_AI_Fix`;
        
        // Format: TEAMNAME_LEADERNAME_AI_Fix
        return `${team}_${leader}_AI_Fix`;
    };

    const branchName = generateBranchName(form.team_name, form.leader_name);

    const set = (field) => (e) => {
        setForm(prev => ({ ...prev, [field]: e.target.value }));
        setError('');  // Clear error on any input change
    };

    const handleSubmit = async () => {
        // Client-side validation
        if (!form.github_url.trim()) {
            setError('Repository URL is required.');
            return;
        }
        if (!form.github_url.trim().startsWith('https://github.com/')) {
            setError('Invalid URL. Must start with https://github.com/');
            return;
        }
        // Check URL has owner/repo format
        const path = form.github_url.trim().replace('https://github.com/', '').replace('.git', '');
        const parts = path.split('/');
        if (parts.length < 2 || !parts[0] || !parts[1]) {
            setError('Invalid URL format. Expected: https://github.com/owner/repo');
            return;
        }
        if (!form.team_name.trim()) {
            setError('Team Name is required.');
            return;
        }
        if (!form.leader_name.trim()) {
            setError('Leader Name is required.');
            return;
        }

        setLoading(true);
        setError('');

        try {
            const result = await startRun({
                github_url: form.github_url.trim(),
                team_name: form.team_name.trim(),
                leader_name: form.leader_name.trim()
                // branch_name will be auto-generated by backend
            });
            setCurrentRunId(result.job_id);
            setScreen('results');
        } catch (err) {
            // The backend returns { detail: "..." } for validation errors
            setError(err.message || 'Failed to start run. Check the backend logs.');
            setLoading(false);
        }
    };

    return (
        <div style={styles.container}>
            <div style={styles.card}>
                <div style={styles.header}>
                    <span className="material-icons" style={styles.rocket}>rocket_launch</span>
                    <h2 style={styles.heading}>New Run</h2>
                    <p style={styles.subtext}>Configure and launch a new healing agent run</p>
                </div>

                {/* Error Banner */}
                {error && (
                    <div style={styles.errorBanner}>
                        <span className="material-icons" style={styles.errorIcon}>warning</span>
                        <span>{error}</span>
                    </div>
                )}

                {/* Form */}
                <div style={styles.form}>
                    <div style={styles.field}>
                        <label style={styles.label}>Repository URL *</label>
                        <input
                            style={styles.input}
                            placeholder="https://github.com/owner/repo"
                            value={form.github_url}
                            onChange={set('github_url')}
                            disabled={loading}
                        />
                    </div>

                    <div style={styles.row}>
                        <div style={styles.fieldHalf}>
                            <label style={styles.label}>Team Name *</label>
                            <input
                                style={styles.input}
                                placeholder="e.g. Neural Ninjas"
                                value={form.team_name}
                                onChange={set('team_name')}
                                disabled={loading}
                            />
                        </div>
                        <div style={styles.fieldHalf}>
                            <label style={styles.label}>Leader Name *</label>
                            <input
                                style={styles.input}
                                placeholder="e.g. John Doe"
                                value={form.leader_name}
                                onChange={set('leader_name')}
                                disabled={loading}
                            />
                        </div>
                    </div>

                    <div style={styles.field}>
                        <label style={styles.label}>Branch Name (Auto-generated)</label>
                        <input
                            style={{...styles.input, ...styles.readonlyInput}}
                            placeholder="Will be generated from team and leader names"
                            value={branchName}
                            readOnly
                            disabled
                        />
                        {branchName && (
                            <div style={styles.hint}>
                                <span className="material-icons" style={{fontSize: '14px', color: 'var(--green)'}}>check_circle</span> Branch will be created as: <span style={styles.branchPreview}>{branchName}</span>
                            </div>
                        )}
                    </div>
                </div>

                {/* Actions */}
                <div style={styles.actions}>
                    <button
                        style={styles.backBtn}
                        onClick={() => setScreen('dashboard')}
                        disabled={loading}
                    >
                        <span className="material-icons" style={{fontSize: '16px', marginRight: '4px'}}>arrow_back</span> Back
                    </button>
                    <button
                        style={{
                            ...styles.submitBtn,
                            opacity: loading ? 0.6 : 1,
                            cursor: loading ? 'not-allowed' : 'pointer'
                        }}
                        onClick={handleSubmit}
                        disabled={loading}
                    >
                        {loading ? (
                            <><span className="material-icons rift-spinner" style={{fontSize: '16px', marginRight: '6px'}}>progress_activity</span> Validating & Starting...</>
                        ) : (
                            <><span className="material-icons" style={{fontSize: '16px', marginRight: '6px'}}>play_arrow</span> Start Run</>
                        )}
                    </button>
                </div>
            </div>
        </div>
    );
}

const styles = {
    container: {
        display: 'flex',
        justifyContent: 'center',
        alignItems: 'center',
        minHeight: 'calc(100vh - 60px)',
        padding: '20px'
    },
    card: {
        background: 'var(--card)',
        border: '1px solid var(--border)',
        borderRadius: '10px',
        padding: '40px 48px',
        width: '100%',
        maxWidth: '580px'
    },
    header: {
        textAlign: 'center',
        marginBottom: '28px'
    },
    rocket: {
        fontSize: '36px',
        display: 'block',
        marginBottom: '8px'
    },
    heading: {
        fontSize: '20px',
        fontWeight: 600,
        color: 'var(--text)',
        marginBottom: '4px'
    },
    subtext: {
        color: 'var(--text-dim)',
        fontSize: '13px'
    },
    errorBanner: {
        background: 'rgba(248,81,73,0.1)',
        border: '1px solid rgba(248,81,73,0.3)',
        borderRadius: '6px',
        padding: '12px 16px',
        marginBottom: '20px',
        fontSize: '13px',
        color: '#f85149',
        display: 'flex',
        alignItems: 'flex-start',
        gap: '8px',
        lineHeight: 1.5
    },
    errorIcon: {
        fontSize: '14px',
        flexShrink: 0,
        marginTop: '1px'
    },
    form: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px'
    },
    field: {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px'
    },
    fieldHalf: {
        display: 'flex',
        flexDirection: 'column',
        gap: '6px',
        flex: 1
    },
    row: {
        display: 'flex',
        gap: '12px'
    },
    label: {
        fontSize: '11px',
        fontWeight: 600,
        color: 'var(--text-dim)',
        textTransform: 'uppercase',
        letterSpacing: '0.5px'
    },
    input: {
        padding: '10px 14px',
        background: 'var(--bg)',
        border: '1px solid var(--border)',
        borderRadius: '6px',
        color: 'var(--text)',
        fontSize: '14px',
        outline: 'none'
    },
    readonlyInput: {
        background: 'var(--card2)',
        color: 'var(--text-dim)',
        cursor: 'not-allowed',
        fontFamily: 'JetBrains Mono, monospace',
        fontSize: '13px'
    },
    hint: {
        fontSize: '11px',
        color: 'var(--text-dim)',
        marginTop: '4px',
        display: 'flex',
        alignItems: 'center',
        gap: '4px'
    },
    branchPreview: {
        color: 'var(--green)',
        fontFamily: 'JetBrains Mono, monospace',
        fontSize: '11px',
        fontWeight: 600
    },
    actions: {
        display: 'flex',
        justifyContent: 'space-between',
        marginTop: '28px'
    },
    backBtn: {
        padding: '10px 20px',
        background: 'transparent',
        border: '1px solid var(--border)',
        borderRadius: '6px',
        color: 'var(--text-dim)',
        fontSize: '13px',
        cursor: 'pointer'
    },
    submitBtn: {
        padding: '10px 24px',
        background: 'var(--green)',
        color: 'var(--bg)',
        borderRadius: '6px',
        fontSize: '14px',
        fontWeight: 600,
        cursor: 'pointer',
        border: 'none',
        transition: 'opacity 0.2s'
    }
};
